language: scala
jdk:
- oraclejdk8

cache:
  directories:
    - "$HOME/.ivy2/cache"
    - "$HOME/.sbt/boot"
    - "$HOME/.sbt/launchers"
    - "$HOME/.coursier"

before_script:
  - bash -xe ./run_gitbucket.sh

script:
  - bash -xe ./build_all.sh && python3 merge_json.py

after_script:
  - ls dist
  - cat dist/plugins.json
  - cat ~/gitbucket.log

deploy:
  provider: releases
  api_key: "$GITHUB_TOKEN"
  skip_cleanup: true
  file_glob: true
  file: dist/*
  on:
    tags: true