language: scala
jdk:
- oraclejdk8

cache:
  directories:
    - "$HOME/.ivy2"
    - "$HOME/.sbt"

script:
  - bash -xe ./build_all.sh

after_script:
  - python3 merge_json.py
  - ls dist
  - cat dist/plugins.json

deploy:
  provider: releases
  api_key: "$GITHUB_TOKEN"
  skip_cleanup: true
  file_glob: true
  file: dist/*
  on:
    tags: true