language: scala
jdk:
- oraclejdk8
addons:
  apt:
    packages:
    - npm

cache:
  apt: true
  directories:
    - "$HOME/.ivy2/cache"
    - "$HOME/.sbt/boot"
    - "$HOME/.sbt/launchers"
    - "$HOME/.coursier"
    - "$HOME/.npm"
    - "$HOME/Downloads"

before_cache:
  # Cleanup the cached directories to avoid unnecessary cache updates
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete

before_script:
  - mkdir -p $HOME/Downloads
  - bash -xe ./run_gitbucket.sh

script:
  - bash ./build_all.sh

after_script:
  - ls dist
  - cat dist/plugins.json
  - cat ~/gitbucket.log

deploy:
  provider: releases
  api_key: "$GITHUB_TOKEN"
  skip_cleanup: true
  file_glob: true
  file: dist/*
  on:
    tags: true