#!/bin/sh

PLUGIN_BUILD_ENABLED=true

PLUGIN_REPOSITORY_OWNER=gitbucket-plugins
PLUGIN_REPOSITORY_NAME=gitbucket-h2-backup-plugin

PLUGIN_ID=h2-backup
PLUGIN_NAME="H2 Database Backup Plugin"
PLUGIN_DESCRIPTION="Allows to export the H2 database of GitBucket"
PLUGIN_VERSION=1.6.0
PLUGIN_TAG_NAME=${PLUGIN_VERSION}

PLUGIN_IS_DEFAULT=false

PLUGIN_PROJECT_URL=https://github.com/${PLUGIN_REPOSITORY_OWNER}/${PLUGIN_REPOSITORY_NAME}

PLUGIN_SRC_TGZ_URL=https://github.com/${PLUGIN_REPOSITORY_OWNER}/${PLUGIN_REPOSITORY_NAME}/archive/${PLUGIN_TAG_NAME}.tar.gz
PLUGIN_SRC_DIR=${PLUGIN_REPOSITORY_NAME}-${PLUGIN_TAG_NAME}

PLUGIN_JAR=target/scala-2.12/gitbucket-${PLUGIN_ID}-plugin-assembly-${PLUGIN_VERSION}.jar
