#!/bin/sh

PLUGIN_NAME=ci
PLUGIN_VERSION=1.3.0
PLUGIN_TAG_NAME=${PLUGIN_VERSION}

PLUGIN_REPOSITORY_OWNER=takezoe
PLUGIN_REPOSITORY_NAME=gitbucket-ci-plugin

PLUGIN_TGZ_URL=https://github.com/${PLUGIN_REPOSITORY_OWNER}/${PLUGIN_REPOSITORY_NAME}/archive/${PLUGIN_TAG_NAME}.tar.gz
PLUGIN_SRC_DIR=${PLUGIN_REPOSITORY_NAME}-${PLUGIN_TAG_NAME}

PLUGIN_JAR_FILENAME=gitbucket-${PLUGIN_NAME}-plugin-assembly-${PLUGIN_VERSION}.jar
PLUGIN_JAR_PATH=target/scala-2.12/${PLUGIN_JAR_FILENAME}
